#!/bin/bash
#
# Sets up machine using Ansible, installing it if necessary.
#
set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

function missing_executable() {
  local executable=$1
  ! [ -x "$(command -v ${executable})" ]
}

function upgrade_pip() {
  if missing_executable pip3; then
    echo "pip3 not found"
    exit 1
  fi
  echo "Upgrading pip3"
  sudo -H pip3 install --upgrade pip
}

function install_brew() {
  if missing_executable brew; then
    upgrade_pip
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
}

function install_ansible() {
  if missing_executable ansible-playbook; then
    upgrade_pip
    echo "Installing Ansible"
    sudo pip3 install ansible
  fi
}

function apply_playbook() {
  echo "Applying Ansible playbook"
  cd "$SCRIPT_DIR/ansible"
  export ANSIBLE_NOCOWS=1
  ansible-playbook -i inventory --ask-become-pass playbook.yml
}

echo "Setting up machine"
install_brew
install_ansible
apply_playbook
echo "Finished setting up machine"
